version: '3'

services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - backend

  frontend:
    restart: always
    build: ./frontend
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    networks:
      - backend

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
